### ISSUE TITLE
The "code" argument must be of type number. Received type string 

### ISSUE THREAD

**Issue by cikichen** [Minionguyjpro/Inno-Setup-Action#100]
node:internal/errors:541
      throw error;
      ^
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_CHILD_PROCESS_STDIO_M...')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:180:24)
    at D:\actions-runner\_work\_actions\Minionguyjpro\Inno-Setup-Action\v1.2.5\dist\index.js:26632:19
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v20.13.1

**Comment by zhycheng614** [comment]
I have the same question

**Comment by Minionguyjpro** [comment]
I think I replied on AI too much for this. I think I know how to fix this though.

**Comment by zhycheng614** [comment]
> I think I replied on AI too much for this. I think I know how to fix this though.

So how to solve this problem?

**Comment by Minionguyjpro** [comment]
Maybe not sure, but I will look into this somewhere next week.

**Comment by Minionguyjpro** [comment]
> node:internal/errors:541
>       throw error;
>       ^
> TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_CHILD_PROCESS_STDIO_M...')
>     at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
>     at process.exit (node:internal/process/per_thread:180:24)
>     at D:\actions-runner\_work\_actions\Minionguyjpro\Inno-Setup-Action\v1.2.5\dist\index.js:26632:19
>     at ChildProcess.exithandler (node:child_process:430:5)
>     at ChildProcess.emit (node:events:519:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> Node.js v20.13.1

Could you show me your workflow?

**Comment by cikichen** [comment]
> > node:internal/errors:541
> > throw error;
> > ^
> > TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_CHILD_PROCESS_STDIO_M...')
> > at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
> > at process.exit (node:internal/process/per_thread:180:24)
> > at D:\actions-runner_work_actions\Minionguyjpro\Inno-Setup-Action\v1.2.5\dist\index.js:26632:19
> > at ChildProcess.exithandler (node:child_process:430:5)
> > at ChildProcess.emit (node:events:519:28)
> > at maybeClose (node:internal/child_process:1105:16)
> > at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
> > code: 'ERR_INVALID_ARG_TYPE'
> > }
> > Node.js v20.13.1
> 
> Could you show me your workflow?

I switched to using `choco install innosetup --yes`.
